### ISSUE TITLE
False positive for require

### ISSUE THREAD

**Issue by tuxmaster** [voxpupuli/puppet-lint-resource_reference_syntax#10]
Example:
require     => File[tomcat8_dir]
will mark as an Error:
ERROR: resource reference with title with capital letter on line
when gem puppet-lint-resource_reference_syntax is installed.
Other used gem's:
gem list

*** LOCAL GEMS ***

abrt (0.0.6)
bigdecimal (1.2.0)
io-console (0.4.2)
json (1.7.7)
psych (2.0.0)
puppet-lint (2.0.0, 1.1.0)
puppet-lint-top_scope_facts-check (0.0.1)
puppet-lint-trailing_newline-check (1.0.0)
puppet-lint-unquoted_string-check (0.3.0)
puppet-lint-variable_contains_upcase (1.0.1)
rdoc (4.0.0)

**Comment by domcleal** [comment]
The resource reference is missing quotes (see https://github.com/voxpupuli/puppet-lint-resource_reference_syntax#resource_reference_without_title_capital). Can you add them and check if the lint error goes away?

**Comment by tuxmaster** [comment]
Yes, this was it.
Thanks
