### ISSUE TITLE
false resource_reference_without_whitespace on resource collection

### ISSUE THREAD

**Issue by langesven** [voxpupuli/puppet-lint-resource_reference_syntax#15]
Since updating the gem to latest (1.0.11) I'm seeing some issues with whitespace errors on resource collectors.
Picked the example from #9 to illustrate:
```
package { 'htop':
  ensure => latest,
}
Sshkeys::Set_authorized_key <<| tag == $::facts[fqdn] |>>
```
yields
> ERROR: whitespce between reference type and title on line 4

while
```
Sshkeys::Set_authorized_key <<| tag == $::facts[fqdn] |>>
```
on its own yields no errors.

The more definitions are prior to the collector the more alleged errors are printed.
```
service { 'puppet':
  ensure => running,
}
package { 'less':
  ensure => latest,
}
package { 'htop':
  ensure => latest,
}
Sshkeys::Set_authorized_key <<| tag == $::facts[fqdn] |>>
```
> ERROR: whitespce between reference type and title on line 10
ERROR: whitespce between reference type and title on line 10
ERROR: whitespce between reference type and title on line 10

The same files checked against version 1.0.10 do not throw any errors.

**Comment by tuxmea** [comment]
Thanks for the issue report. I added new spec tests and built a new version also to rubygems.org.
